Ext.define('TrxResearch.model.clearing.Record', {
    extend: 'Ext.data.Model',



    fields: [
        { name: 'DE31' , type: 'auto' },
        { name: 'PDS0148' , type: 'auto' },
        { name: 'PDS0149' , type: 'auto' },
        { name: 'PDS0502' , type: 'auto' },
        { name: 'MTI' , type: 'auto' },
        { name: 'DE71' , type: 'auto' },
        { name: 'PDS0025' , type: 'auto' },
        { name: 'PDS0146' , type: 'auto' },
        { name: 'PDS0147' , type: 'auto' },
        { name: 'DE100' , type: 'auto' },
        { name: 'PDS0190' , type: 'auto' },
        { name: 'PDS0195' , type: 'auto' },
        { name: 'PDS0196' , type: 'auto' },
        { name: 'DE26' , type: 'auto' },
        { name: 'PDS0197' , type: 'auto' },
        { name: 'PDS0198' , type: 'auto' },
        { name: 'DE24' , type: 'auto' },
        { name: 'PDS0191' , type: 'auto' },
        { name: 'DE23' , type: 'auto' },
        { name: 'PDS0071' , type: 'auto' },
        { name: 'PDS0192' , type: 'auto' },
        { name: 'DE22' , type: 'auto' },
        { name: 'DE42' , type: 'auto' },
        { name: 'PDS0214' , type: 'auto' },
        { name: 'DE41' , type: 'auto' },
        { name: 'PDS0215' , type: 'auto' },
        { name: 'DE40' , type: 'auto' },
        { name: 'PDS0056' , type: 'auto' },
        { name: 'PDS0177' , type: 'auto' },
        { name: 'PDS0057' , type: 'auto' },
        { name: 'DE111' , type: 'auto' },
        { name: 'DE38' , type: 'auto' },
        { name: 'DE37' , type: 'auto' },
        { name: 'DE33' , type: 'auto' },
        { name: 'DE32' , type: 'auto' },
        { name: 'DE51' , type: 'auto' },
        { name: 'DE50' , type: 'auto' },
        { name: 'DE94' , type: 'auto' },
        { name: 'PDS0206' , type: 'auto' },
        { name: 'DE93' , type: 'auto' },
        { name: 'PDS0001' , type: 'auto' },
        { name: 'PDS0002' , type: 'auto' },
        { name: 'PDS0003' , type: 'auto' },
        { name: 'PDS0207' , type: 'auto' },
        { name: 'DE2' , type: 'auto' },
        { name: 'DE4' , type: 'auto' },
        { name: 'DE3' , type: 'auto' },
        { name: 'DE6' , type: 'auto' },
        { name: 'DE5' , type: 'auto' },
        { name: 'PDS0052' , type: 'auto' },
        { name: 'DE9' , type: 'auto' },
        { name: 'DE49' , type: 'auto' },
        { name: 'PDS0175' , type: 'auto' },
        { name: 'PDS0176' , type: 'auto' },
        { name: 'PDS0170' , type: 'auto' },
        { name: 'DE43' , type: 'auto' },
        { name: 'PDS0159' , type: 'auto' },
        { name: 'DE63' , type: 'auto' },
        { name: 'PDS0199' , type: 'auto' },
        { name: 'PDS0158' , type: 'auto' },
        { name: 'entityId' , type: 'auto' },
        { name: 'recNumber' , type: 'auto' },
        { name: 'PDS0080' , type: 'auto' },
        { name: 'PDS0043' , type: 'auto' },
        { name: 'DE14' , type: 'auto' },
        { name: 'PDS0165' , type: 'auto' },
        { name: 'DE12' , type: 'auto' },
        { name: 'DE55' , type: 'auto' },
        { name: 'PDS0160' , type: 'auto' },
        { name: 'DE10' , type: 'auto' },
        { name: 'DE54', type: 'auto' }

    ]
});
