Ext.define('TrxResearch.model.Record', {
    extend: 'Ext.data.Model',

    statics: {
        getStatusName: function(status) {
            return this.prototype.statusNames[status];
        },

        getTxnMtiName: function(txnMti) {
            return this.prototype.txnMtiNames[txnMti];
        }
    },

    fields: [
        { name: 'recordId', type: 'auto' },
        { name: 'envId', type: 'auto' },
        { name: 'envTimeIn', type: 'auto' },
        { name: 'safPlanId', type: 'auto' },
        { name: 'txnMti', type: 'auto' },
        { name: 'issuerBin', type: 'auto' },
        { name: 'issuerId', type: 'auto' },
        { name: 'serviceCode', type: 'auto' },
        { name: 'eciInd', type: 'auto' },
        { name: 'ucafInd', type: 'auto' },
        { name: 'pinInd', type: 'auto' },
        { name: 'inGateId', type: 'auto' },
        { name: 'outGateId', type: 'auto' },
        { name: 'inNodeId', type: 'auto' },
        { name: 'outNodeId', type: 'auto' },
        { name: 'inGateTimeIn', type: 'auto' },
        { name: 'inGateTimeOut', type: 'auto' },
        { name: 'outGateTimeIn', type: 'auto' },
        { name: 'outGateTimeOut', type: 'auto' },
        { name: 'exportStatus', type: 'auto' },
        { name: 'txnF1', type: 'auto' },
        { name: 'txnF2', type: 'auto' },
        { name: 'txnF3', type: 'auto' },
        { name: 'txnF4', type: 'auto' },
        { name: 'txnF5', type: 'auto' },
        { name: 'txnF6', type: 'auto' },
        { name: 'txnF7', type: 'auto' },
        { name: 'txnF8', type: 'auto' },
        { name: 'txnF9', type: 'auto' },
        { name: 'txnF10', type: 'auto' },
        { name: 'txnF11', type: 'auto' },
        { name: 'txnF12', type: 'auto' },
        { name: 'txnF13', type: 'auto' },
        { name: 'txnF14', type: 'auto' },
        { name: 'txnF15', type: 'auto' },
        { name: 'txnF16', type: 'auto' },
        { name: 'txnF17', type: 'auto' },
        { name: 'txnF18', type: 'auto' },
        { name: 'txnF19', type: 'auto' },
        { name: 'txnF20', type: 'auto' },
        { name: 'txnF21', type: 'auto' },
        { name: 'txnF22', type: 'auto' },
        { name: 'txnF23', type: 'auto' },
        { name: 'txnF24', type: 'auto' },
        { name: 'txnF25', type: 'auto' },
        { name: 'txnF26', type: 'auto' },
        { name: 'txnF27', type: 'auto' },
        { name: 'txnF28', type: 'auto' },
        { name: 'txnF29', type: 'auto' },
        { name: 'txnF30', type: 'auto' },
        { name: 'txnF31', type: 'auto' },
        { name: 'txnF32', type: 'auto' },
        { name: 'txnF33', type: 'auto' },
        { name: 'txnF34', type: 'auto' },
        { name: 'txnF35', type: 'auto' },
        { name: 'txnF36', type: 'auto' },
        { name: 'txnF37', type: 'auto' },
        { name: 'txnF38', type: 'auto' },
        { name: 'txnF39', type: 'auto' },
        { name: 'txnF40', type: 'auto' },
        { name: 'txnF41', type: 'auto' },
        { name: 'txnF42', type: 'auto' },
        { name: 'txnF43', type: 'auto' },
        { name: 'txnF44', type: 'auto' },
        { name: 'txnF45', type: 'auto' },
        { name: 'txnF46', type: 'auto' },
        { name: 'txnF47', type: 'auto' },
        { name: 'txnF48', type: 'auto' },
        { name: 'txnF49', type: 'auto' },
        { name: 'txnF50', type: 'auto' },
        { name: 'txnF51', type: 'auto' },
        { name: 'txnF52', type: 'auto' },
        { name: 'txnF53', type: 'auto' },
        { name: 'txnF54', type: 'auto' },
        { name: 'txnF55', type: 'auto' },
        { name: 'txnF56', type: 'auto' },
        { name: 'txnF57', type: 'auto' },
        { name: 'txnF58', type: 'auto' },
        { name: 'txnF59', type: 'auto' },
        { name: 'txnF60', type: 'auto' },
        { name: 'txnF61', type: 'auto' },
        { name: 'txnF62_2', type: 'auto' },
        { name: 'txnF63_2', type: 'auto' }

    ],

    statusNames: {
        '0': '0'
    },

    txnMtiNames: {
        '0100': 'Authorization (0100)',
        '0120': 'Advice (0120)',
        '0200': '0200',
        '0400': 'Reversal (0400)',
        '0401': '0401',
        '0420': 'Reversal Advice (0420)',
        '0600': '0600'
    }
});
